### ISSUE TITLE
Exponential notation

### ISSUE THREAD

**Issue by oldgristmill** [mcguirepr89/BirdNET-Pi#171]
Now that I have my Pi set up and running in a decent location, I'm getting overwhelmed with waxwing and robin identifications (probably because the box is currently near a well-stocked rowan/mountain ash tree). So, in the "top 10" hourly grid, I've noted that it displays number >100 in exponential notation., crowding them out in the graph. (Hundreds of robin IDs in the first hour... must be spring!)

Also, the scroll bar has disappeared on all the webpages the BirdNet-Pi creates... in both Chrome and Microsoft Edge. Not sure if this is a reproduceable problem for others, but happened in both browsers for me.

**Comment by mcguirepr89** [comment]
Hi, @oldgristmill! This is fixed in `newif` and will be pulled into `main` soon.

Feel free to test out the `newif` branch if you'd like -- I always appreciate [the feedback](https://github.com/mcguirepr89/BirdNET-Pi/discussions/11)!

On a clean installation, install with:
```
curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Pi/main/newinstaller.sh | bash
```

Take a look at the [known bugs and issues](https://github.com/mcguirepr89/BirdNET-Pi/discussions/11#discussioncomment-2422312) for that branch and let me know anything else you find!

My best regards!

PS
I will keep this open until I merge `newif` into `main`
