### ISSUE TITLE
current version of Installer does not work

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#289]
Serveral errors during the installation:

![grafik](https://user-images.githubusercontent.com/14326464/169029674-5e906324-13cf-4697-811d-7412d7a19e12.png)

![grafik](https://user-images.githubusercontent.com/14326464/169029781-db5eedcb-a655-4c3e-8d39-9102ff88fb72.png)

![grafik](https://user-images.githubusercontent.com/14326464/169029872-9106a4f9-c7c9-452f-81c8-b46d0a7032a3.png)

**Comment by mgzob** [comment]
I hit this wall yesterday. I -believe- this is the full set of commands required to unblock the install.

> sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
> sudo apt update
> sudo apt install caddy
> sudo apt-get install python3-venv python3-dev sqlite3

Note: Some are not required; I believe debian-keyring / others may already be sorted? I also don't remember if I added `icecast2` or not. If you do include icecast2, you don't need to do any configuration during install.

**Comment by mcguirepr89** [comment]
Hello!

There is an issue upstream with Caddy's newest GPG key signature -- it will need to get sorted out upstream. It likely works sometimes and not others due to DNS caching of the old key signature location since the URL is the same. I suspect this glitch will not last long. It's hard to say when it started, but likely in the last few days shortly after the version update from caddy. I was able to install caddy today using the installation excerpt @mgzob mentions, so it _seems_ that is has been fixed. Please let me know if you still see the error on your next installation attempt -- if so, I may look into mimicking their setup script within the BirdNET-Pi installer and then include the `caddy` binary to have one less thing "upstream" on which we must depend for stability.

**Comment by DD4WH** [comment]
Perfect!
Thank you, @mgzob and @mcguirepr89 

* I issued all the commands in this comment https://github.com/mcguirepr89/BirdNET-Pi/issues/289#issuecomment-1130273053
* and then started the usual one-line-installer 
* It took two attempts (the first attempt gave a network error after some minutes), not sure why . . . maybe a network failure here at home.
* now it works!

**Comment by mcguirepr89** [comment]
Caddy updated the documentation for Debian installations, so [this](https://github.com/mcguirepr89/BirdNET-Pi/commit/354fce1aaf69b1f6f5a6d4a55689ce10e5f812db) possibly fixed the installer. Let me know!

**Comment by DD4WH** [comment]
Thanks a lot, Patrick !!! With the latest installer it works perfectly as usual with the one-line-installer and without the additional commands!

Thanks also, @mgzob for your help and the commands, which also worked when I installed the former version yesterday.
