### ISSUE TITLE
Multiple Incorrect Apprise Notifications

### ISSUE THREAD

**Issue by abartow91** [mcguirepr89/BirdNET-Pi#296]
I want to start with how much I love BirdnetPi and appreciate all the work that has put in it.  It's an awesome project!  My wife, who is the birder/researcher in the family is so excited by it.

We have the apprise notifications setup to email each of us when a new species is detected.  This part works mostly.
It does email us when a new species is detected, but it doesn't list the confidence at all.

But it also will (seemingly) randomly email us a list of all species detected with the email "New Species Detected" subject.

This is the email we receive:
Subject: New Species Detected
Body: New Species Detection: American Crow  American Robin  Baltimore Oriole  Barn Owl  Barred Owl  Blackpoll Warbler  Blue Jay  Bohemian Waxwing  Broad-winged Hawk  Brown-headed Cowbird  Brown-headed Nuthatch  Brown Thrasher  Canada Goose  Cape May Warbler  Carolina Chickadee  Carolina Wren  Cedar Waxwing  Chimney Swift  Chipping Sparrow  Common Grackle  Common Nighthawk  Common Yellowthroat  Downy Woodpecker  Eastern Bluebird  Eastern Screech-Owl  Eastern Towhee  Eastern Wood-Pewee  European Starling  Fish Crow  Gray Catbird  Great Crested Flycatcher  Greater Prairie-Chicken  House Finch  Mourning Dove  Northern Cardinal  Northern Flicker  Northern Mockingbird  Orchard Oriole  Pileated Woodpecker  Pine Warbler  Purple Martin  Red-bellied Woodpecker  Red-cockaded Woodpecker  Red-shouldered Hawk  Rose-breasted Grosbeak  Ruby-throated Hummingbird  Rusty Blackbird  Scarlet Tanager  Summer Tanager  Tufted Titmouse  Veery  White-breasted Nuthatch  Wood Thrush  Yellow-billed Cuckoo  Yellow-throated Vireo 

Today, we received this email about 10 times so far.
I've attached a copy of the logs from the web terminal between 9:10 am and 9:18 am
In that time, we received an email at 9:11am, 9:12am, and two at 9:16am

I've also attached a screenshot of the notification settings (emails blurred out).
Since you can't see the full notification body, it is the default:
A $sciname $comname was just detected with a confidence of $confidence
Also on a restart of the BirdnetPi, the enabling of "Notify each new Species" is deselected and I have to go in and check it.

Things I've tried:
Adding a second email address
Restarting the Pushed Notification Services
Rebooting BirdnetPi from the menu
Cycling Power on my rasberry Pi

Thanks for your help! Let me know if you need any other information
[Birdnet_Log_20220520_0910_t
![BirdnetPi_Notification_Settings](https://user-images.githubusercontent.com/86199835/169541599-5c711a1e-18bf-4729-abbb-7d0175675b2c.PNG)
hru_0918.txt](https://github.com/mcguirepr89/BirdNET-Pi/files/8740614/Birdnet_Log_20220520_0910_thru_0918.txt)

**Comment by ehpersonal38** [comment]
Hi @abartow91!

Thanks so much for the feedback and the detailed description of the issue! It makes my job a lot easier.

>We have the apprise notifications setup to email each of us when a new species is detected. This part works mostly.
It does email us when a new species is detected, but it doesn't list the confidence at all.

This is admittedly how it's coded. The "new species" system is actually completely separate from the "new detection" system. I've been meaning to get the two joined together, so that I can properly access confidence info for the "new species" system, but haven't gotten around to it yet. 

So this means Notification title & Notification body are only for "Notify each new detection," for now.

>Also on a restart of the BirdnetPi, the enabling of "Notify each new Species" is deselected and I have to go in and check it.

I can't replicate this myself. Maybe you could post the output of `service pushed_notifications status` right after a reboot?

>Today, we received this email about 10 times so far.

This is very strange, but it is @mcguirepr89's code, so I'll pass this part over to him if he would be so gracious as to investigate :)

**Comment by mcguirepr89** [comment]
I think I want to do away with `species_notifier.sh` and instead alter `server.py` to check for another variable, `APPRISE_NOTIFY_NEW_SPECIES`, that will use the same logic as `APPRISE_NOTIFY_EACH_DETECTION`. Then do away with the `pushed_notification.service`. It makes more sense this way and you'll get the notification more quickly (only by a few seconds). It will also use what is configured in "Settings". I'll let you all know when that's put together--it will make its way into the open PR more than likely.

**Comment by ehpersonal38** [comment]
Exactly what I was thinking! Thanks Patrick!

**Comment by mcguirepr89** [comment]
On second thought, I think I'll do this on another branch and pull that into main, then we can pull from `main` on the PR fork (just a heads up, @jmherbst)

**Comment by mcguirepr89** [comment]
Howdy, folks. I just wanted to provide an update here:
I fixed this yesterday and then let my installations (and the un-pushed changes) get destroyed in a rain storm yesterday evening. I just wanted to let you all know that I didn't drop this like a hot tamale and should be pushing the fixes sometime later today.

**Comment by mcguirepr89** [comment]
> Even in a Tupperware container and with that wood housing it got destroyed? Wow...

No!! I've moved since that setup, and did not have the tried and true lunch meat container protection!!!! I went into the city last night and then it rained HARDDDDDD for several hours -- when I got back both of my pis were literally sitting in a puddle (fan still running somehow!!!) Once I'm able to get things re-built, suffice it to say I'll be eating a lot of lunch meat until my BirdNET-Pis feel safe!

Great ideas -- I'll tinker with that after properly adding the new species notifier

**Comment by ehpersonal38** [comment]
Hahaha!!!! 

This might help btw:
`select Count(*) from Detections where Com_Name = "Boat-tailed Grackle" AND date > (SELECT DATETIME('now', '-7 day'))`

**Comment by mcguirepr89** [comment]
@abartow91 This is been fixed! Please update to get the fix and do let me know (save the output) if you have any issues updating~~

My very best regards,
Patrick

**Comment by mcguirepr89** [comment]
Very glad the notifications are meeting your needs! Happy birding!! Please don't forget to share any great pictures, spectrograms, recordings, etc [with the community](https://github.com/mcguirepr89/BirdNET-Pi/discussions/69) -- hopefully the new notifications will enable you to catch a glimpse of that rare species just in time!
