### ISSUE TITLE
Flickr image search with languages other than english

### ISSUE THREAD

**Issue by kaeltis** [mcguirepr89/BirdNET-Pi#313]
I've just enabled the Flickr images for bird detections and noticed that some species return images of completely different things due to different meanings of words in different languages.

For example, the German name for [Sturnus vulgaris](https://wikipedia.org/wiki/Sturnus_vulgaris) is "Star", which obviously returns a bunch of pictures of stars in BirdNET-Pi.

Possible solutions I can think of:

- Use the scientific names for the image search on Flickr
- As a possible fallback or alternative, use the english names instead of the translated ones
- According to https://www.flickr.com/services/api/flickr.photos.search.html the search can be extended with tags, this could be set to "bird" and "bird" in the language the birdname is in, so for the german bird name "Star" search for "Star" and use the tags "bird,vogel"

**Comment by ehpersonal38** [comment]
Thanks for this issue report! I've tried the solutions you proposed and I think the only solid one is #2. Since Flickr is a primarily English website, trying to search bird names in other languages _does_ work for some, but for many languages it returns little to no usable results.

So I think we need to have labels_en.txt permanently on the Pi somewhere, and the PHP that handles searching Flickr can do a grep of that file to get the English name from the scientific name.

**Comment by ehpersonal38** [comment]
Okay I've gone ahead and pushed this. 45c05ea427a07e9f8e54f6bb9945a287085b0c39

@kaeltis 
You will need to:
1) Tools -> System Controls -> Update
2) Clear cookies for your BirdNET-Pi URL. (on chrome that's here: chrome://settings/siteData?searchSubpage=birdnet)

Try this out and please report back if it works for you!

**Comment by ehpersonal38** [comment]
#314 has been fixed! aba67608754f7024d73cfed7b0265cd9c00081b9 969e5928bbcd0a98a4dd9a2f2a769690804dca5e
Best Recordings has been updated! 138a03159117deb88a8d3f6cdb2ed126d8d40194

Closing now, thanks for the issue :)
