### ISSUE TITLE
Possible to add known ring tones and other sounds as Ignored matches

### ISSUE THREAD

**Issue by jeff-luszcz** [mcguirepr89/BirdNET-Pi#329]
I commonly get matches to birds that are due to passerby's phones ringing with common ring tones

For example the common iPhone ringtone 'Xylophone" shows up as a Ridgeways Rail match

I could exclude that bird (which maybe is the easiest) but if there was a "reject list" of common sounds that could be a method of suppressing common false positives

**Comment by mcguirepr89** [comment]
Hi, @jeff-luszcz Thanks for installing BirdNET-Pi and for your great suggestion.
I would love that!!! I would add various snippets of me singing to my cats -- most of their favorites about being bad girls, mostly -- but it would require retraining the model for those sounds, and that's not quite within the scope of BirdNET-Pi. You might mention that to @kahst over at https://github.com/kahst/BirdNET-Analyzer.git for the new model as it is being actively trained.

I'm going to close this issue, since it's not something we'll be able to address -- in the meantime, as you mentioned, you can add the "Ridgeways Rail" to your "Excluded Species List" and that would take care of it for now.

My best regards,
Patrick
