### ISSUE TITLE
RTSP stream does not work

### ISSUE THREAD

**Issue by Ulflindberg** [mcguirepr89/BirdNET-Pi#855]
**Describe the bug**
As soon as I add a RTSP stream to be the source birdnet pi stops working. 
**To Reproduce**
I remove the RTSP stream and start the log and I can see that the Birdnet works. Adding the RTSP stream again and opens the log and I can see in the log that RTPS stream is addad but then nothing happens.

**Expected behavior**
My earlier installation worked very well with RTSP stream but after update it does not work
**Screenshots**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/34133928/232184092-3b07b857-2e30-464b-a33b-0234f685c56e.png">

**Additional context**
Add any other context about the problem or your installation here.

**Your build**
Raspberrypi 3

**Code or log snippets**
```
Paste your 
log output 
or 
code here
```

**Comment by jaredb7** [comment]
Hi @Ulflindberg 

This wouldn't be a RTSP stream from a Ubiquiti camera would it? (just noticed the port is all), at camera identifier hash thing at the end). 
If so they seem to have 2 audio streams which confuses the recording system after it updated to enable simultaneous RTSP recording... it doesn't know what audio to stream to use. It worked before because we weren't playing with output mapping.

Can you try running this ffprobe command via SSH or via Tools -> Web Terminal, just double check the URL as I just typed it from your screenshot.

`ffprobe -hide_banner -show_streams -of json  rtsp://192.168.4.1:7447/YBSisVM3cgwjElyq`

From the output, check if there are 2 audio streams, example screenshot below
![image](https://user-images.githubusercontent.com/799998/232307165-775f6cf7-e4e1-478e-8f7f-49aeec7dd31b.png)

If so, you'll need a workaround to get recording going again, can you edit the birdnet_recording.sh file used by the bird using Tools -> File Manager, then browse to **/ pi / BirdNET-Pi / scripts**
![image](https://user-images.githubusercontent.com/799998/232307439-8b6762cc-8f8b-453d-a4f9-732498051b90.png)

Find birdnet_recording.sh, edit it and add `:a:0` after `${MAP_ID}` ... so it becomes `${MAP_ID}:a:0`.
Save and restart the Recording service under Tools -> Services
Recording
![image](https://user-images.githubusercontent.com/799998/232307484-2fa0264e-164c-466d-85fc-3b414bb61816.png)

Let me know how you go.

**Comment by Ulflindberg** [comment]
Hi @jaredb7 ,

Yes it is a Ubiquiti camera and I have edited the file as you suggested and now it seems to be running. I have just restarded so I will let it run and see that everything works before celebrating. Thanks a lot for your help.

Ulf

**Comment by Ulflindberg** [comment]
It has now been running for a few hours and works really good.

**Comment by jaredb7** [comment]
Awesome great to hear it's working :) , we hope to have that fix implemented properly soon so it'll just work.
